CREATE OR REPLACE VIEW HEROES AS
    SELECT 
        UNIT_CASTLE.UNIT_NAME, 
        UNIT_CASTLE.CASTLE_NAME,
        UNIT_LEVEL.UNIT_LEVEL,
        UNIT_INFO.GOLD,
        UNIT_INFO.SPEED,
        UNIT_INFO.ATTACK
    FROM
        UNIT_CASTLE JOIN UNIT_LEVEL
        ON UNIT_CASTLE.UNIT_NAME = UNIT_LEVEL.UNIT_NAME
        JOIN UNIT_INFO
        ON UNIT_LEVEL.UNIT_NAME = UNIT_INFO.UNIT_NAME;